url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Harry Baines

postcss:
  cache: false

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

collections:
  pages:
    output: true
    permalink: /:path
  projects:
    output: true
    permalink: /:path

permalink: pretty

navigation:
  - title: Projects
    url: /projects.html
  - title: Posts
    url: /posts.html
  - title: About
    url: /about.html

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - .gitignore

plugins:
  - jekyll-toc

social:
  twitter: https://twitter.com/harryb0905
  github: https://github.com/harrybaines
  kaggle: https://www.kaggle.com/harrybaines
  linkedin: https://www.linkedin.com/in/harry-baines-400609137/